/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2025-04-04 04:41:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import jsp0404.DBConnection;
import java.sql.Connection;

public final class input_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./component/header.jsp", Long.valueOf(1743741316763L));
    _jspx_dependants.put("/./component/footer.jsp", Long.valueOf(1743738192846L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("jsp0404.DBConnection");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Connection conn = DBConnection.getConnection();
String sql = "SELECT T_CODE, T_NAME FROM TBL_LAB_TEST_202004";
PreparedStatement pstmt = conn.prepareStatement(sql);
ResultSet rs = pstmt.executeQuery();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>진단검사 프로그램 ver 2020-04</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<div>\r\n");
      out.write("		<a href=\"index.jsp\">\r\n");
      out.write("			(과정평가형 정보처리산업기사)진단검사 프로그램 ver 2020-04\r\n");
      out.write("		</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<nav>\r\n");
      out.write("		<ul class=\"gnb\">\r\n");
      out.write("			<li><a href='view.jsp'>환자조회</a></li>\r\n");
      out.write("			<li><a href='input.jsp'>검사결과입력</a></li>\r\n");
      out.write("			<li><a href='result_view.jsp'>검사결과조회</a></li>\r\n");
      out.write("			<li><a href='location_view.jsp'>지역별검사건수</a></li>\r\n");
      out.write("			<li><a href='index.jsp'>홈으로</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<section class=\"title\">\r\n");
      out.write("			<h2>검사결과입력</h2>\r\n");
      out.write("		</section>\r\n");
      out.write("		<section class=\"content\">\r\n");
      out.write("			<form onsubmit=\"return check()\" method=\"post\" action=\"input_action.jsp\">\r\n");
      out.write("				<table border=\"1\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>환자번호</td>\r\n");
      out.write("						<td><input name=\"P_NO\" data-alert=\"환자번호가 입력되지 않았습니다\">예)1001</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>검사코드</td>\r\n");
      out.write("						<td><select name=\"T_CODE\">\r\n");
      out.write("								<option>검사명</option>\r\n");
      out.write("								");

								while (rs.next()) {
								
      out.write("\r\n");
      out.write("								<option value=");
      out.print(rs.getString("T_CODE"));
      out.write('>');
      out.print(rs.getString("T_NAME"));
      out.write("</option>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("						</select></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>검사시작일자</td>\r\n");
      out.write("						<td><input name=\"T_SDATE\" data-alert=\"검사시작일자가 입력되지 않았습니다\">예)20200101</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>검사상태</td>\r\n");
      out.write("						<td><input name=\"T_STATUS\" value=\"1\" type=\"radio\" checked data-alert=\"검사상태가 선택되지 않았습니다\">검사중\r\n");
      out.write("							<input name=\"T_STATUS\" value=\"2\" type=\"radio\" data-alert=\"검사상태가 선택되지 않았습니다\">검사완료</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>검사완료일자</td>\r\n");
      out.write("						<td><input name=\"T_LDATE\" data-alert=\"검사완료일자가 입력되지 않았습니다\">예)20200101</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>검사결과</td>\r\n");
      out.write("						<td><input name=\"T_RESULT\" data-alert=\"검사결과가 선택되지 않았습니다\" value=\"X\" type=\"radio\" checked>미입력\r\n");
      out.write("							<input name=\"T_RESULT\" data-alert=\"검사결과가 선택되지 않았습니다\" value=\"P\" type=\"radio\">양성 <input\r\n");
      out.write("							name=\"T_RESULT\" data-alert=\"검사결과가 선택되지 않았습니다\" value=\"N\" type=\"radio\">음성</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"2\">\r\n");
      out.write("							<button type=\"submit\">검사결과등록</button>\r\n");
      out.write("							<button type=\"button\" onclick=\"resetHandler()\">다시쓰기</button>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</table>\r\n");
      out.write("			</form>\r\n");
      out.write("		</section>\r\n");
      out.write("	</main>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("	<h3>\r\n");
      out.write("		HRDKOREA Copyright&copy;2020 All rights reserved. Human Resources Development Service of Korea\r\n");
      out.write("		</h3>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	function check() {\r\n");
      out.write("		let flag = false;\r\n");
      out.write("		\r\n");
      out.write("		document.querySelectorAll(\"input\").forEach(input => {\r\n");
      out.write("			if(!input.value && !flag) {\r\n");
      out.write("				flag = true;\r\n");
      out.write("				alert(input.dataset.alert);\r\n");
      out.write("				input.focus();\r\n");
      out.write("				return\r\n");
      out.write("			} \r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		if(document.querySelector(\"select\").value === \"검사명\" && !flag) {\r\n");
      out.write("			alert(\"검사코드가 선택되지 않았습니다\")\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(flag) return false;\r\n");
      out.write("		\r\n");
      out.write("		alert(\"검사결과가 정상적으로 등록되었습니다!\");\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function resetHandler() {\r\n");
      out.write("		alert(\"정보를 지우고 처음부터 다시 입력합니다!\");\r\n");
      out.write("		location.reload();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");

DBConnection.close(rs, pstmt, conn);

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
